name: ci

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (lean)
        run: |
          python -m pip install --upgrade pip
          pip install dvc[gdrive] black ruff

      # Verifica que el pipeline es válido (no ejecuta stages ni baja datos)
      - name: Validate DVC graph
        run: |
          dvc --version
          dvc dag
          dvc status -q || true  # parsea dvc.yaml; no falla por falta de datos

      # Lint básico (sin formatear)
      - name: Lint (ruff + black --check)
        run: |
          ruff check .
          black --check .
